package wallet

const ERROR_WALLET = 0x40000

const ERROR_WALLET_NOT_FOUND_ID = ERROR_WALLET + 1

const ERROR_WALLET_NOT_FOUND = ERROR_WALLET + 2

const ERROR_WALLET_VALUE = ERROR_WALLET + 3

const ERROR_WALLET_STATUS = ERROR_WALLET + 4

const ERROR_WALLET_ACTION = ERROR_WALLET + 5

const ERROR_WALLET_ORDER_NAME = ERROR_WALLET + 6
